"""Message database model.

Represents a single message within a conversation, sent by either
the user or the AI assistant.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


class Message(Base):
    """Represents a single message within a conversation.

    Attributes:
        id: Unique UUID primary key.
        conversation_id: The parent conversation's id.
        role: Who sent the message — "user" or "assistant".
        content: The message text.
        total_tokens: Token usage for this message, if generated by AI.
        created_at: Timestamp of creation.
        conversation: The parent Conversation this message belongs to.
    """

    __tablename__ = "messages"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    conversation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("conversations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    role: Mapped[str] = mapped_column(String(20), nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    total_tokens: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    conversation: Mapped["Conversation"] = relationship("Conversation", back_populates="messages")

    def __repr__(self) -> str:
        """Return a developer-friendly string representation.

        Returns:
            A string showing the message's id and role.
        """
        return f"<Message id={self.id} role={self.role}>"